baseURL = 'https://juliangallegog.github.io/'
languageCode = 'en-us'
title = 'Julián Gallego - Personal Portfolio'
theme = 'gokarna'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 5